const books = [
  {
    id: 1,
    Name:"IT END WITH US",
    auther: "Ahmed",
    category: "comedy",
    pages: 40,
    price: 100,
    image: "images/1_.jpg",
    instore:1,
  },
  {
    id: 2,
    Name:"PUNK",
    auther: "Nyraa",
    category: "Homour",
    pages: 70,
    price: 150,
    instore:1,
    image: "images/2_.jpg",
  },
  {
    id: 3,
    Name:"When i am",
    auther: "Esraa",
    category: "Romantic",
    pages: 25,
    price: 50,
    instore:1,
    image: "images/3_.jpg",
  },
  {
    id: 4,
    Name:"COLLEEN",
    auther: "Ahmed",
    category: "comedy",
    pages: 150,
    price: 200,
    instore:1,
    image: "images/4_.jpg",
  },
  {
    id: 5,
    Name:"Start with us",
    auther: "Osama",
    category: "comedy",
    pages: 230,
    price: 220,
    instore:1,
    image: "images/5_.jpg",
  },
  {
    id: 6,
    Name:"Things we never got over",
    auther: "Ahmed",
    category: "comedy",
    pages: 35,
    price: 50,
    instore:1,
    image: "images/6_.jpg",
  },
];
export default books;
